### ISSUE TITLE
Source-free Domain Adaptation via Avatar Prototype Generation and Adaptation相关

### ISSUE THREAD

**Issue by Lorraine-Kwok** [qiuzhen8484/all_code#1]
你好，非常感谢您之前做的无源域适应CPGA的相关工作，想问您可否开放一下针对office-31数据集的相关代码，我尝试复现性能但失败了，谢谢！

**Comment by qiuzhen8484** [comment]
谢谢关注，对于所有的数据集（VisDA、Office-31、Office-Home）模型训练测试代码都是一致的，换一下数据集为https://github.com/SCUT-AILab/CPGA/blob/4412e1a9b996b1cb0a1ba4dec6c968f7b447d113/dataset.py#L97，
 不过注意为了公平比较，和现存方法一样，训练集和测试集是同一个(训练源模型则是9：1分用于保存源模型)，只需改一下配置参数num_class、lr=1e-3, https://github.com/SCUT-AILab/CPGA/blob/4412e1a9b996b1cb0a1ba4dec6c968f7b447d113/train_visda.py#L397 这的num_classes，网络改为resnet50

**Comment by Lorraine-Kwok** [comment]
谢谢您的详细指导！麻烦您了，我也是一名研究无源域适应的学生，之前论文中的学校邮箱无法联系上您，请问您可否更新一个邮箱呢？非常感谢您的回复

**Comment by Lorraine-Kwok** [comment]
前辈~还有一个问题就是发现在训练visda-17的时候，loss出现了负值，这个现象怎么解决呢

**Comment by qiuzhen8484** [comment]
loss出现负值是正常的，跟elr loss有关，可以联系这个邮箱qiuzhenscut@gmail.com

**Comment by Lorraine-Kwok** [comment]
好的好的，太感谢你了！祝您科研顺利~~~~
